apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: ragops-sentinel
  labels:
    app.kubernetes.io/name: rag-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ragops-sentinel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rag-api
  ports:
    - name: http
      port: 8000
      targetPort: http
